# Generated by Django 5.1.2 on 2025-05-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_register', '0002_developer_copy_review_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
